### ISSUE TITLE
Krieger function not found

### ISSUE THREAD

**Issue by munshimdrasel** [idblr/ndi#1]
Hy,
While checking the codes, I am seeing the krieger function is not working. How can I resolve this issue?

Error in krieger(state = "TX", year = 2020) : 
  could not find function "krieger"

Thanks
Rasel

**Comment by idblr** [comment]
Hi Rasel, 

The `krieger()` function is currently available in the development version (v0.1.2.9000) available from GitHub. You can download this version using the following code:

```r
devtools::install_github("idblr/ndi")
```

After some bug fixes in the next few weeks, I will submit an updated release to CRAN

**Comment by idblr** [comment]
The `krieger()` function is now available in the release version (v0.1.2) available on [CRAN](https://cran.r-project.org/package=ndi)
