### ISSUE TITLE
Refactoring to Allow for Existing Data

### ISSUE THREAD

**Issue by chris-prener** [idblr/ndi#2]
Great work on `ndi`, @idblr! 

I'd love to integrate your package into some existing workflows, but would like to be able to pass a data frame of correctly prepped/formatted data to `messer()` or one of the other functions. 

The [`sociome` package](https://github.com/NikKrieger/sociome) has a great workaround that allows this, the [`calculate_adi()` function](https://github.com/NikKrieger/sociome/blob/master/R/calculate_adi.R). Instead of calling the main `get_adi()` function that downloads the data and calculates ADI, users with pre-existing data can skip the download step by calling `calculate_adi()` directly.

I'm wondering if you'd be open to a PR that would create (as an example) a `calculate_messer()` function that `messer()` would call as a subfunction after data download and prep. I would also export it so that other workflows could call it directly. I'm most interested in this for `messer()` and `powell_wiley()`, but would happily write it for `anthopolos()`, `bravo()`, and `krieger()` as well (doesn't make sense to do it for `gini()`). Thanks for considering!

**Comment by idblr** [comment]
Thanks @chris-prener!

I was expecting this feature. In an upcoming release, I am creating a new argument in the `messer()` function, for example, that toggles between calculating the metric with a pre-existing prepared data frame or (if NULL) downloading the data using the internal `tidycensus::get_acs()` function. Would that work for your purposes?

The `sociome` package has a nice compartmentalized structure to their functions. Reworking `ndi` to match this structure would be an overhaul and take some extra documentation, tests, etc. Happy to chat options to help `ndi` fit within your workflow and others!

**Comment by chris-prener** [comment]
> I was expecting this feature. In an upcoming release, I am creating a new argument in the messer() function, for example, that toggles between calculating the metric with a pre-existing prepared data frame or (if NULL) downloading the data using the internal tidycensus::get_acs() function. Would that work for your purposes?

Yes - that would be great - it should meet the needs of the work we're doing!

**Comment by idblr** [comment]
@chris-prener, check out a new branch [dev_input_df](https://github.com/idblr/ndi/tree/dev_input_df) with an initial version of the requested feature (ndi v0.1.2.9001)

The `messer()` and `powell_wiley()` functions have a new argument `df` that allows users to input a pre-formated `tbl_df` `tbl`, or `data.frame` object to compute the respective NDIs. Note the structure of the data input, I aimed for simplicity and flexibility. For the `messer()` function, the data input should have an ID as the first feature (column) followed by any data as subsequent features (columns). For the `messer()` function, the data input should have an ID as the first feature (column), an estimate of the total population in the second feature (column), followed by any data as subsequent features (columns). 

The branch passes CRAN checks, but feedback about the new `df` argument, structure, and documentation is welcomed. The `df` argument could be added to other metrics if of interest.

**Comment by chris-prener** [comment]
Sorry my attention got pulled away from this project for a few days @idblr ! I'm going to check this out today.

**Comment by chris-prener** [comment]
Thanks again for working on this, @idblr! In principle I think this approach would work. Would you be willing to relax the requirement for tract/county if folks are "bringing their own" data? That's also important to me, since I rarely have the luxury of working at the tract level. I would suggest moving the check down into [this section](https://github.com/idblr/ndi/blob/8a65deaa9807951f2d6b3e62e026d39eb65cc490/R/messer.R#L78). 

I'm not sure how you'd suggest navigating [this part](https://github.com/idblr/ndi/blob/8a65deaa9807951f2d6b3e62e026d39eb65cc490/R/messer.R#L260) because I was only planning to supply `GEOID` plus `OOC`, `CWD`, etc (not state and county). One possibility would be to see if `state` and `county` (and `tract`) are present in the input data and subset columns accordingly?

**Comment by idblr** [comment]
Good catch, @chris-prener!

Yes, the check for `geo` and `year` arguments should be activated only if `df = NULL`. I will move these check below the `if (is.null(df))` [line 
](https://github.com/idblr/ndi/blob/8a65deaa9807951f2d6b3e62e026d39eb65cc490/R/messer.R#L78), for example.

Also, if `df = NULL`, the function output will not include any additional information (columns, features) that is not already included in the `df` input. The code is admittedly messy at the moment with all the if-else statements, but [this line](https://github.com/idblr/ndi/blob/8a65deaa9807951f2d6b3e62e026d39eb65cc490/R/messer.R#L274) is the formatting of the output if `df = NULL`, where the first column is an ID, followed by the NDI values, and supplied variables. So I do not suspect the output formatting related to the `df` needs modification, but let me know if so.

You can find the changes to `messer()` and `powell_wiley()` in a [recent commit](https://github.com/idblr/ndi/commit/4cf0cd6499a6055778f8adfc2d05b8516b43cdfc) to the[dev_input_df](https://github.com/idblr/ndi/tree/dev_input_df) branch. The branch passes CRAN checks again, but let me know if something else comes up. I'll resubmit to CRAN in a few weeks, but hopefully, the dev version is OK for your purposes now.

**Comment by chris-prener** [comment]
That all sounds great! Thanks for working with me on this. I'd be happy to support refactoring code if you want a PR!

**Comment by idblr** [comment]
@chris-prener, a PR sounds great. I'll merge the [dev_input_df](https://github.com/idblr/ndi/tree/dev_input_df) branch with the [main](https://github.com/idblr/ndi) branch, and you can pull the update. I'll close this issue for now.
