### ISSUE TITLE
Significant Digits

### ISSUE THREAD

**Issue by chris-prener** [idblr/ndi#3]
One additional question that popped up in `messer()` is the [rounding that takes place at the end](https://github.com/idblr/ndi/blob/feeef3267f58145ad5c3e5244d9e65990845407a/R/messer.R#L230). I'm sure you had a reason for doing it! Just curious your thoughts about whether that should be optional?

**Comment by idblr** [comment]
@chris-prener, I agree the rounding should be optional. Rounding the raw census data was implemented in the initial releases to match the output of the data provided by the NHLBI [ADOPT Core Measures](https://gis.cancer.gov/research/adopt.html), see [Socioeconomic Deprivation](https://gis.cancer.gov/research/files.html#soc-dep) to replicate their approach with the `powell_wiley()` function.

I believe not rounding in future releases is the better approach; users can round after the calculation. Or would you prefer an additional argument?

**Comment by chris-prener** [comment]
Especially if you're replicating prior work, it makes sense to provide something that gets you as close as possible to the original estimates. I might suggest an argument with a logical scalar - something like `round_output` where `TRUE` allows you to match prior work and `FALSE` returns data without rounding?

**Comment by idblr** [comment]
Great idea, @chris-prener. I've opened a new [dev_round_output](https://github.com/idblr/ndi/tree/dev_round_output) branch and [commit](https://github.com/idblr/ndi/commit/a03480cac0923faff64f194e7c91143287449e24) to add the suggested `round_output` argument to the functions. The default is `FALSE`, no rounding.  

The branch passes CRAN checks, but feedback about the new `round_output` argument, structure, and documentation is welcomed.

**Comment by chris-prener** [comment]
makes sense to me @idblr!
