### ISSUE TITLE
NDIQuint Sorting Question with Powell-Wiley

### ISSUE THREAD

**Issue by chris-prener** [idblr/ndi#4]
hey @idblr! I've been doing more testing and found something curious that I'm hoping you can straighten out for me. 

```r
df <- ndi::powell_wiley(geo = "county", state = "MO", year = 2020, round_output = FALSE)[[1]]
df <- dplyr::arrange(df, NDI)
```

On rows 69 and 70 of the resulting `df` object, Barry County (`29009`) gets a score of `0.24683105` while Sullivan County (`29211`) gets a score of `0.26129508`. However, in `NDIQunit`, Barry County is given `4-AboveAvg deprivation` while Sullivan is given `3-Average deprivation`. 

This is possible because the [log of the total population](https://github.com/idblr/ndi/blob/a1c5b780202dfe57db52a7c2cf6fa998cab29b4e/R/powell_wiley.R#L295) is factored into the ranking process, correct?

**Comment by idblr** [comment]
@chris-prener, yes this is because the NDI (Powell-Wiley) method weights the categorical metric by total population of each geography

**Comment by chris-prener** [comment]
Thanks for the quick confirmation!
