### ISSUE TITLE
GitHub Actions and NDI on ubuntu-latest (oldrel-2)

### ISSUE THREAD

**Issue by chris-prener** [idblr/ndi#8]
Hey @idblr! Thanks for keeping this package kicking - it's such a great contribution! We're about to release a package that has wrappers around a couple of the NDI indices, and noticed that we can't pass R CMD check on GitHub Actions for `ubuntu-latest (oldrel-2)` and older. Also noticed that your GitHub Actions workflow stops with `ubuntu-latest (oldrel-1)`, and that your `DESCRIPTION` file suggests R 3.5 should be supported. Any insight on what is going on with older releases?

```r
── R CMD check results ────────────────────────────── deprivateR 0.1.0.9000 ────
Duration: 1.2s

❯ checking package dependencies ... ERROR
Error:   Package required but not available: ‘ndi’
  
  See section ‘The DESCRIPTION file’ in the ‘Writing R Extensions’
  manual.

1 error ✖ | 0 warnings ✔ | 0 notes ✔
Error: Error: R CMD check found ERRORs
Execution halted
Error: Process completed with exit code 1.
```

**Comment by idblr** [comment]
@chris-prener Thanks for your continued interest in the 'ndi' package. I have removed the GitHub Action for R-CMD-Check for `ubuntu-latest (oldrel-1)`

`DESCRIPTION` depends on R (>= 3.5.0). This roughly matches its major dependency 'tidycensus' and its compatibility with R (>=3.3.0). Are you recommending earlier or later R version compatibility?

**Comment by chris-prener** [comment]
Gotcha - no - the `ubuntu-latest (oldrel-1)` was fine! You should put it back :) - sorry for the confusioN!

I was hitting issues with `ubuntu-latest (oldrel-2)`, `ubuntu-latest (oldrel-3)`, and `ubuntu-latest (oldrel-4)`. I'm curious if you know what's up with those? Should be well beyond 3.5!

**Comment by chris-prener** [comment]
This also might help now that we've open sourced our package - here are the [GitHub actions results](https://github.com/pfizer-opensource/deprivateR/actions/runs/9861339295) for `R CMD check`

**Comment by idblr** [comment]
@chris-prener I'll take a look under the hood. Thanks for sharing the `R CMD check` for 'deprivatR'

FYI, are you familiar with the ['findSVI'](https://cran.r-project.org/package=findSVI) package on CRAN for calculating CDC SVI? Seems relevant to your upcoming package.

**Comment by chris-prener** [comment]
I was not aware of `findSVI` - thanks for sharing!

**Comment by idblr** [comment]
@chris-prener  OK, looks like the error in GitHub Actions `R CMD check` pertains to dependencies.

The largest dependency was GDAL, PROJ, and GEOS for 'sf' on `macOS-latest` and `ubuntu-latest` machines. Other dependencies were for 'DescTools' and 'pbkrtest' (a dependency of 'car') which depend on `R (>= 4.2.0)` and are unavailable for `ubuntu-latest (oldrel-3)` or older.

So I will keep a `devel`, `release`, and `oldrelease` for `ubuntu-latest` but not specify older `ubuntu-latest` releases.
